// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Blog Home documents
 */
interface BlogHomeDocumentData {
  /**
   * Meta Description field in *Blog Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Home document from Prismic
 *
 * - **API ID**: `blog_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogHomeDocumentData>,
    "blog_home",
    Lang
  >;

type BlogPostDocumentDataSlicesSlice =
  | PostTitleSliceSlice
  | PostImageSliceSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Main Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Post Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.post_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  post_title: prismic.KeyTextField;

  /**
   * Post Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.post_author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  post_author: prismic.KeyTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Post Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.post_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  post_description: prismic.KeyTextField;

  /**
   * category field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.categoty
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoty: prismic.ContentRelationshipField<"category">;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *FAQ → FaqQuestion*
 */
export interface FaqDocumentDataFaqquestionItem {
  /**
   * Question field in *FAQ → FaqQuestion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faqquestion[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ → FaqQuestion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faqquestion[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

type FaqDocumentDataSlicesSlice = FaqSliceSlice;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * FaqTitle field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faqtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faqtitle: prismic.KeyTextField;

  /**
   * FaqQuestion field in *FAQ*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.faqquestion[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqquestion: prismic.GroupField<Simplify<FaqDocumentDataFaqquestionItem>>;

  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice>
  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *homepage → menuItens*
 */
export interface HomepageDocumentDataMenuitensItem {
  /**
   * Link Title field in *homepage → menuItens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menuitens[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * link field in *homepage → menuItens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menuitens[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *homepage → Content Menu Options*
 */
export interface HomepageDocumentDataContentMenuOptionsItem {
  /**
   * Link Title field in *homepage → Content Menu Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.content_menu_options[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link field in *homepage → Content Menu Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.content_menu_options[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *homepage → Social Links*
 */
export interface HomepageDocumentDataSocialLinksItem {
  /**
   * icon field in *homepage → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *homepage → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type HomepageDocumentDataSlicesSlice =
  | CallToSurveySlice
  | CustomerLogosSlice
  | TestimonialsSliceSlice
  | WelcomeSliceSlice
  | CardsSlice
  | NewsletterSlotSlice
  | ContactFormSliceSlice
  | IframeCardSliceSlice
  | SocialTriggersSliceSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * logo field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * menuItens field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menuitens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menuitens: prismic.GroupField<Simplify<HomepageDocumentDataMenuitensItem>>;

  /**
   * Call To Action Text field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.call_to_action_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_text: prismic.KeyTextField;

  /**
   * Menu Footer Title field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.menu_footer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  menu_footer_title: prismic.RichTextField;

  /**
   * Content Footer Title field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.content_footer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content_footer_title: prismic.RichTextField;

  /**
   * Content Menu Options field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.content_menu_options[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content_menu_options: prismic.GroupField<
    Simplify<HomepageDocumentDataContentMenuOptionsItem>
  >;

  /**
   * Phone Number field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone_number: prismic.TitleField;

  /**
   * Email IndHuge field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * Social footer title field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.social_footer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  social_footer_title: prismic.RichTextField;

  /**
   * Social Links field in *homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<HomepageDocumentDataSocialLinksItem>
  >;

  /**
   * Copyright Text field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright_text: prismic.KeyTextField;

  /**
   * PopUpTitle field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.popuptitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  popuptitle: prismic.KeyTextField;

  /**
   * PopUpText field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.popuptext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  popuptext: prismic.RichTextField;

  /**
   * PopUpImage field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.popupimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  popupimage: prismic.ImageField<never>;

  /**
   * PopUpCloseText field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.popupclosetext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  popupclosetext: prismic.KeyTextField;

  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type QuizDocumentDataSlicesSlice = QuizQustionSliceSlice;

/**
 * Content for Quiz documents
 */
interface QuizDocumentData {
  /**
   * Slice Zone field in *Quiz*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<QuizDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: quiz.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Quiz*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Quiz*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: quiz.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Quiz document from Prismic
 *
 * - **API ID**: `quiz`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuizDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<QuizDocumentData>, "quiz", Lang>;

/**
 * Item in *Survey → Questions*
 */
export interface SurveyDocumentDataQuestionsItem {
  /**
   * question Id field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].question_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question_id: prismic.KeyTextField;

  /**
   * Question field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Option A field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].option_a
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_a: prismic.KeyTextField;

  /**
   * Option B field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].option_b
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_b: prismic.KeyTextField;

  /**
   * Option C field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].option_c
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_c: prismic.KeyTextField;

  /**
   * Option D field in *Survey → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[].option_d
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_d: prismic.KeyTextField;
}

type SurveyDocumentDataSlicesSlice = never;

/**
 * Content for Survey documents
 */
interface SurveyDocumentData {
  /**
   * Questions field in *Survey*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<SurveyDocumentDataQuestionsItem>>;

  /**
   * Slice Zone field in *Survey*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SurveyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Survey*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: survey.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Survey*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: survey.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Survey*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: survey.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Survey document from Prismic
 *
 * - **API ID**: `survey`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SurveyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SurveyDocumentData>,
    "survey",
    Lang
  >;

export type AllDocumentTypes =
  | BlogHomeDocument
  | BlogPostDocument
  | CategoryDocument
  | FaqDocument
  | HomepageDocument
  | QuizDocument
  | SurveyDocument;

/**
 * Primary content in *CallToSurvey → Primary*
 */
export interface CallToSurveySliceDefaultPrimary {
  /**
   * Title field in *CallToSurvey → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_survey.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Call To Action field in *CallToSurvey → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_survey.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action: prismic.KeyTextField;

  /**
   * background field in *CallToSurvey → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_survey.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Default variation for CallToSurvey Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToSurveySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToSurveySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToSurvey*
 */
type CallToSurveySliceVariation = CallToSurveySliceDefault;

/**
 * CallToSurvey Shared Slice
 *
 * - **API ID**: `call_to_survey`
 * - **Description**: CallToSurvey
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToSurveySlice = prismic.SharedSlice<
  "call_to_survey",
  CallToSurveySliceVariation
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * mainTitle field in *Cards → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.primary.maintitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  maintitle: prismic.TitleField;

  /**
   * mainText field in *Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.primary.maintext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  maintext: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceDefaultItem {
  /**
   * cardIcon field in *Cards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.items[].cardicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardicon: prismic.ImageField<never>;

  /**
   * cardTitle field in *Cards → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.items[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardtitle: prismic.TitleField;

  /**
   * cardText field in *Cards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.items[].cardtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardtext: prismic.RichTextField;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  Simplify<CardsSliceDefaultItem>
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Primary content in *ContactFormSlice → Primary*
 */
export interface ContactFormSliceSliceDefaultPrimary {
  /**
   * Titulo de Ação field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.actionTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  actionTitle: prismic.TitleField;

  /**
   * Main Title field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_title: prismic.TitleField;

  /**
   * Text Body field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.text_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_body: prismic.RichTextField;

  /**
   * Forms Title field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.forms_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  forms_title: prismic.TitleField;

  /**
   * Name Placeholder field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_placeholder: prismic.KeyTextField;

  /**
   * Email Placeholder field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Phone Placeholder field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.phone_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_placeholder: prismic.KeyTextField;

  /**
   * Message Placeholder field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.message_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_placeholder: prismic.KeyTextField;

  /**
   * Contact Options Placeholder field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.contact_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_placeholder: prismic.KeyTextField;

  /**
   * Contact Options field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.contact_options
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  contact_options: prismic.SelectField<
    "small_company" | "medium_company" | "big_company"
  >;

  /**
   * Send Button Text field in *ContactFormSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_slice.primary.send_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  send_button_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactFormSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSlice*
 */
type ContactFormSliceSliceVariation = ContactFormSliceSliceDefault;

/**
 * ContactFormSlice Shared Slice
 *
 * - **API ID**: `contact_form_slice`
 * - **Description**: ContactFormSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceSlice = prismic.SharedSlice<
  "contact_form_slice",
  ContactFormSliceSliceVariation
>;

/**
 * Primary content in *CustomerLogos → Items*
 */
export interface CustomerLogosSliceDefaultItem {
  /**
   * image field in *CustomerLogos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CustomerLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CustomerLogosSliceDefaultItem>
>;

/**
 * Slice variation for *CustomerLogos*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault;

/**
 * CustomerLogos Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<
  "customer_logos",
  CustomerLogosSliceVariation
>;

/**
 * Default variation for FaqSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FaqSlice*
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;

/**
 * FaqSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: FaqSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSlice = prismic.SharedSlice<
  "faq_slice",
  FaqSliceSliceVariation
>;

/**
 * Primary content in *IframeCardSlice → Primary*
 */
export interface IframeCardSliceSliceDefaultPrimary {
  /**
   * Iframe field in *IframeCardSlice → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: iframe_card_slice.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  iframe: prismic.EmbedField;
}

/**
 * Default variation for IframeCardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeCardSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IframeCardSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IframeCardSlice*
 */
type IframeCardSliceSliceVariation = IframeCardSliceSliceDefault;

/**
 * IframeCardSlice Shared Slice
 *
 * - **API ID**: `iframe_card_slice`
 * - **Description**: IframeCardSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeCardSliceSlice = prismic.SharedSlice<
  "iframe_card_slice",
  IframeCardSliceSliceVariation
>;

/**
 * Primary content in *NewsletterSlot → Primary*
 */
export interface NewsletterSlotSliceDefaultPrimary {
  /**
   * mainText field in *NewsletterSlot → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_slot.primary.maintext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  maintext: prismic.TitleField;

  /**
   * placeholderText field in *NewsletterSlot → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_slot.primary.placeholdertext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholdertext: prismic.KeyTextField;

  /**
   * buttonText field in *NewsletterSlot → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_slot.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttontext: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSlot Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlotSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSlotSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsletterSlot*
 */
type NewsletterSlotSliceVariation = NewsletterSlotSliceDefault;

/**
 * NewsletterSlot Shared Slice
 *
 * - **API ID**: `newsletter_slot`
 * - **Description**: NewsletterSlot
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlotSlice = prismic.SharedSlice<
  "newsletter_slot",
  NewsletterSlotSliceVariation
>;

/**
 * Primary content in *PostImageSlice → Items*
 */
export interface PostImageSliceSliceDefaultItem {
  /**
   * image field in *PostImageSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_image_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Legend field in *PostImageSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_image_slice.items[].image_legend
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_legend: prismic.KeyTextField;
}

/**
 * Default variation for PostImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<PostImageSliceSliceDefaultItem>
>;

/**
 * Slice variation for *PostImageSlice*
 */
type PostImageSliceSliceVariation = PostImageSliceSliceDefault;

/**
 * PostImageSlice Shared Slice
 *
 * - **API ID**: `post_image_slice`
 * - **Description**: PostImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostImageSliceSlice = prismic.SharedSlice<
  "post_image_slice",
  PostImageSliceSliceVariation
>;

/**
 * Primary content in *PostContentSlice → Primary*
 */
export interface PostTitleSliceSliceDefaultPrimary {
  /**
   * Title field in *PostContentSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_title_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *PostContentSlice → Items*
 */
export interface PostTitleSliceSliceDefaultItem {
  /**
   * Content field in *PostContentSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_title_slice.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for PostContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostTitleSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostTitleSliceSliceDefaultPrimary>,
  Simplify<PostTitleSliceSliceDefaultItem>
>;

/**
 * Slice variation for *PostContentSlice*
 */
type PostTitleSliceSliceVariation = PostTitleSliceSliceDefault;

/**
 * PostContentSlice Shared Slice
 *
 * - **API ID**: `post_title_slice`
 * - **Description**: PostTitleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostTitleSliceSlice = prismic.SharedSlice<
  "post_title_slice",
  PostTitleSliceSliceVariation
>;

/**
 * Primary content in *QuizQustionSlice → Primary*
 */
export interface QuizQustionSliceSliceDefaultPrimary {
  /**
   * Question field in *QuizQustionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_qustion_slice.primary.question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * questionId field in *QuizQustionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_qustion_slice.primary.questionid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  questionid: prismic.KeyTextField;

  /**
   * Action field in *QuizQustionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_qustion_slice.primary.action
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action: prismic.KeyTextField;
}

/**
 * Primary content in *QuizQustionSlice → Items*
 */
export interface QuizQustionSliceSliceDefaultItem {
  /**
   * Anwser field in *QuizQustionSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_qustion_slice.items[].anwser
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anwser: prismic.KeyTextField;

  /**
   * Path field in *QuizQustionSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quiz_qustion_slice.items[].path
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  path: prismic.KeyTextField;
}

/**
 * Default variation for QuizQustionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuizQustionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuizQustionSliceSliceDefaultPrimary>,
  Simplify<QuizQustionSliceSliceDefaultItem>
>;

/**
 * Slice variation for *QuizQustionSlice*
 */
type QuizQustionSliceSliceVariation = QuizQustionSliceSliceDefault;

/**
 * QuizQustionSlice Shared Slice
 *
 * - **API ID**: `quiz_qustion_slice`
 * - **Description**: QuizQustionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuizQustionSliceSlice = prismic.SharedSlice<
  "quiz_qustion_slice",
  QuizQustionSliceSliceVariation
>;

/**
 * Primary content in *SocialTriggersSlice → Primary*
 */
export interface SocialTriggersSliceSliceDefaultPrimary {
  /**
   * SocialTriggersSectionTitle field in *SocialTriggersSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_triggers_slice.primary.socialtriggerssectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialtriggerssectiontitle: prismic.KeyTextField;
}

/**
 * Primary content in *SocialTriggersSlice → Items*
 */
export interface SocialTriggersSliceSliceDefaultItem {
  /**
   * SocialTriggerNumber field in *SocialTriggersSlice → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: social_triggers_slice.items[].socialtriggernumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  socialtriggernumber: prismic.NumberField;

  /**
   * SocialTriggerDescription field in *SocialTriggersSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_triggers_slice.items[].socialtriggerdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialtriggerdescription: prismic.KeyTextField;
}

/**
 * Default variation for SocialTriggersSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialTriggersSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialTriggersSliceSliceDefaultPrimary>,
  Simplify<SocialTriggersSliceSliceDefaultItem>
>;

/**
 * Slice variation for *SocialTriggersSlice*
 */
type SocialTriggersSliceSliceVariation = SocialTriggersSliceSliceDefault;

/**
 * SocialTriggersSlice Shared Slice
 *
 * - **API ID**: `social_triggers_slice`
 * - **Description**: SocialTriggersSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialTriggersSliceSlice = prismic.SharedSlice<
  "social_triggers_slice",
  SocialTriggersSliceSliceVariation
>;

/**
 * Primary content in *TestimonialsSlice → Items*
 */
export interface TestimonialsSliceSliceDefaultItem {
  /**
   * customerImage field in *TestimonialsSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.items[].customerimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  customerimage: prismic.ImageField<never>;

  /**
   * Company Name field in *TestimonialsSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.items[].company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * content field in *TestimonialsSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_slice.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TestimonialsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TestimonialsSliceSliceDefaultItem>
>;

/**
 * Slice variation for *TestimonialsSlice*
 */
type TestimonialsSliceSliceVariation = TestimonialsSliceSliceDefault;

/**
 * TestimonialsSlice Shared Slice
 *
 * - **API ID**: `testimonials_slice`
 * - **Description**: TestimonialsSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSlice = prismic.SharedSlice<
  "testimonials_slice",
  TestimonialsSliceSliceVariation
>;

/**
 * Primary content in *WelcomeSlice → Primary*
 */
export interface WelcomeSliceSliceDefaultPrimary {
  /**
   * title field in *WelcomeSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * text field in *WelcomeSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * mainImage field in *WelcomeSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_slice.primary.mainimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainimage: prismic.ImageField<never>;

  /**
   * backgroundImage field in *WelcomeSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_slice.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;
}

/**
 * Default variation for WelcomeSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WelcomeSlice*
 */
type WelcomeSliceSliceVariation = WelcomeSliceSliceDefault;

/**
 * WelcomeSlice Shared Slice
 *
 * - **API ID**: `welcome_slice`
 * - **Description**: WelcomeSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSliceSlice = prismic.SharedSlice<
  "welcome_slice",
  WelcomeSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogHomeDocument,
      BlogHomeDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataFaqquestionItem,
      FaqDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataMenuitensItem,
      HomepageDocumentDataContentMenuOptionsItem,
      HomepageDocumentDataSocialLinksItem,
      HomepageDocumentDataSlicesSlice,
      QuizDocument,
      QuizDocumentData,
      QuizDocumentDataSlicesSlice,
      SurveyDocument,
      SurveyDocumentData,
      SurveyDocumentDataQuestionsItem,
      SurveyDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToSurveySlice,
      CallToSurveySliceDefaultPrimary,
      CallToSurveySliceVariation,
      CallToSurveySliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimary,
      CardsSliceDefaultItem,
      CardsSliceVariation,
      CardsSliceDefault,
      ContactFormSliceSlice,
      ContactFormSliceSliceDefaultPrimary,
      ContactFormSliceSliceVariation,
      ContactFormSliceSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultItem,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      FaqSliceSlice,
      FaqSliceSliceVariation,
      FaqSliceSliceDefault,
      IframeCardSliceSlice,
      IframeCardSliceSliceDefaultPrimary,
      IframeCardSliceSliceVariation,
      IframeCardSliceSliceDefault,
      NewsletterSlotSlice,
      NewsletterSlotSliceDefaultPrimary,
      NewsletterSlotSliceVariation,
      NewsletterSlotSliceDefault,
      PostImageSliceSlice,
      PostImageSliceSliceDefaultItem,
      PostImageSliceSliceVariation,
      PostImageSliceSliceDefault,
      PostTitleSliceSlice,
      PostTitleSliceSliceDefaultPrimary,
      PostTitleSliceSliceDefaultItem,
      PostTitleSliceSliceVariation,
      PostTitleSliceSliceDefault,
      QuizQustionSliceSlice,
      QuizQustionSliceSliceDefaultPrimary,
      QuizQustionSliceSliceDefaultItem,
      QuizQustionSliceSliceVariation,
      QuizQustionSliceSliceDefault,
      SocialTriggersSliceSlice,
      SocialTriggersSliceSliceDefaultPrimary,
      SocialTriggersSliceSliceDefaultItem,
      SocialTriggersSliceSliceVariation,
      SocialTriggersSliceSliceDefault,
      TestimonialsSliceSlice,
      TestimonialsSliceSliceDefaultItem,
      TestimonialsSliceSliceVariation,
      TestimonialsSliceSliceDefault,
      WelcomeSliceSlice,
      WelcomeSliceSliceDefaultPrimary,
      WelcomeSliceSliceVariation,
      WelcomeSliceSliceDefault,
    };
  }
}
