// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cards: dynamic(() => import("./Cards")),
  welcome_slice: dynamic(() => import("./WelcomeSlice")),
};
